// //
// // (C) 2014 RocketChicken Interactive
// // All rights reserved
// //
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Motive.Core.Json;
using Motive.Core.Scripting;

public class AssignmentTask
{
    public string TaskId { get; set; }
    public bool IsRequired { get; set; }
}

public class Assignment : ScriptResource
{
    public string Title { get; set; }
    public string Description { get; set; }
	public string CharacterId {get;set;}
    public AssignmentTask[] Tasks { get; set; }
    public ValuablesCollection Reward { get; set; }
}
