//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Motive.Core.Json;
using Motive.Core.Scripting;
using Motive.Core.Models;

public class CharacterTask : PlayerTask
{
    public ObjectReference CharacterReference { get; set; }
    public string CharacterId
    {
        get
        {
            if (CharacterReference != null)
            {
                return CharacterReference.ObjectId;
            }

            return null;
        }
    }

    public CharacterTask() : this("motive.gaming.characterTask") { }

    public CharacterTask (string objType) : base(objType)
    {
    }
}
