//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using Motive.Core.Json;
using Motive.Core.Models;
using Motive.Core.Scripting;

public class CollectibleCount : ScriptObject
{
    public ObjectReference CollectibleReference;
    public int Count;

    public string CollectibleId
    {
        get
        {
            return CollectibleReference != null ? CollectibleReference.ObjectId : null;
        }
    }

    public CollectibleCount()
    {
        // Default for Count is 1 unless othewise specified
        Count = 1;
    }

    public CollectibleCount(string collectibleId, int count)
    {
        CollectibleReference = new ObjectReference { ObjectId = collectibleId };
        Count = count;
    }

    public override string ToString ()
    {
        return string.Format ("[CollectibleCount: CollectibleId={0}, Count={1}]", CollectibleId, Count);
    }
}
