//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using Motive.Core.Json;
using Motive.Core.Scripting;

public class ValuablesCollection : ScriptResource
{
    public CollectibleCount[] CollectibleCounts { get; set; }
    public CurrencyCount[] CurrencyCounts { get; set; }
    public ValuablesCollection() : base("valuablesCollection") {}
}
